/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jshih.application;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JCheckBox;

import jshih.application.listeners.AttributeListener;
import jshih.application.listeners.BusinessRowListener;
import jshih.application.listeners.LocationListener;
import jshih.application.listeners.MainCategoryListener;
import jshih.application.listeners.SearchListener;
import jshih.application.listeners.SubCategoryListener;
import jshih.application.services.BusinessQuerier;
import jshih.application.services.CategoryQuerier;
import jshih.application.services.ReviewQuerier;
import jshih.model.AppConfiguration;

/**
 *
 * @author jys
 */
public class Application extends javax.swing.JFrame {
    private transient Connection conn;
    private transient CategoryQuerier categoryQuerier;
    private transient BusinessQuerier businessQuerier;
    private transient ReviewQuerier reviewQuerier;

    /**
     * Creates new form Application
     * 
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    public Application() throws ClassNotFoundException, SQLException {
        try {
            this.conn = AppConfiguration.getConnection();
            categoryQuerier = new CategoryQuerier(conn);
            businessQuerier = new BusinessQuerier(conn);
            reviewQuerier = new ReviewQuerier(conn);
        } catch (ClassNotFoundException | SQLException e1) {
            this.conn = null;
            e1.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewDialog = new javax.swing.JDialog();
        reviewDialogPanel = new javax.swing.JScrollPane();
        reviewResultTable = new javax.swing.JTable();
        attributePanel = new javax.swing.JScrollPane();
        attrInnerPanel = new javax.swing.JPanel();
        mainCategoryPanel = new javax.swing.JScrollPane();
        mainInnerPanel = new javax.swing.JPanel();
        businessResultPanel = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        subCategoryPanel = new javax.swing.JScrollPane();
        subInnerPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        othersPanel = new javax.swing.JPanel();
        dayLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        mainSearchForLabel = new javax.swing.JLabel();
        mainSearchForBox = new javax.swing.JComboBox<>();
        daysBox = new javax.swing.JComboBox<>();
        fromBox = new javax.swing.JComboBox<>();
        locationBox = new javax.swing.JComboBox<>();
        toBox = new javax.swing.JComboBox<>();
        subSearchForLabel = new javax.swing.JLabel();
        attrSearchForLabel = new javax.swing.JLabel();
        subSearchForBox = new javax.swing.JComboBox<>();
        attrSearchForBox = new javax.swing.JComboBox<>();

        reviewResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Review Date", "User", "Stars", "Review Text", "Funny Votes", "Cool Votes", "Useful Votes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reviewDialogPanel.setViewportView(reviewResultTable);

        javax.swing.GroupLayout reviewDialogLayout = new javax.swing.GroupLayout(reviewDialog.getContentPane());
        reviewDialog.getContentPane().setLayout(reviewDialogLayout);
        reviewDialogLayout.setHorizontalGroup(
            reviewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reviewDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
        );
        reviewDialogLayout.setVerticalGroup(
            reviewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reviewDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        attrInnerPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        attributePanel.setViewportView(attrInnerPanel);

        generateMainCategories();

        mainInnerPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        mainCategoryPanel.setViewportView(mainInnerPanel);

        resultTable.addMouseListener(new BusinessRowListener(this));

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "City", "State", "Stars", "Reviews", "Checkins", "BusinessUId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        businessResultPanel.setViewportView(resultTable);
        if (resultTable.getColumnModel().getColumnCount() > 0) {
            resultTable.getColumnModel().getColumn(7).setMinWidth(0);
            resultTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            resultTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        subInnerPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        subCategoryPanel.setViewportView(subInnerPanel);

        searchButton.addActionListener(new SearchListener(this));
        searchButton.setText("Search");

        dayLabel.setText("Day of the week");

        locationLabel.setText("Location");

        fromLabel.setText("From");

        toLabel.setText("To");

        mainSearchForLabel.setText("Search for main");

        mainSearchForBox.addActionListener(new MainCategoryListener(this));
        mainSearchForBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND", "OR" }));

        locationBox.addActionListener(new LocationListener(this));

        subSearchForLabel.setText("Search for sub");

        attrSearchForLabel.setText("Search for attribute");

        subSearchForBox.addActionListener(new SubCategoryListener(this));
        subSearchForBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND", "OR" }));

        attrSearchForBox.addActionListener(new AttributeListener(this));
        attrSearchForBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND", "OR" }));

        javax.swing.GroupLayout othersPanelLayout = new javax.swing.GroupLayout(othersPanel);
        othersPanel.setLayout(othersPanelLayout);
        othersPanelLayout.setHorizontalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(othersPanelLayout.createSequentialGroup()
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(othersPanelLayout.createSequentialGroup()
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationLabel))
                        .addGap(36, 36, 36)
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daysBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayLabel)))
                    .addGroup(othersPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainSearchForBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainSearchForLabel))
                        .addGap(116, 116, 116)
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subSearchForLabel)
                            .addComponent(subSearchForBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(othersPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromLabel)
                            .addComponent(fromBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLabel)))
                    .addGroup(othersPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attrSearchForLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(attrSearchForBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        othersPanelLayout.setVerticalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(othersPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainSearchForLabel)
                    .addComponent(subSearchForLabel)
                    .addComponent(attrSearchForLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainSearchForBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attrSearchForBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subSearchForBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayLabel)
                    .addComponent(fromLabel)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(othersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainCategoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subCategoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attributePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(businessResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainCategoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(subCategoryPanel)
                    .addComponent(attributePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(businessResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(othersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateMainCategories() {
        List<String> categories = List.of();
        try {
            categories = this.categoryQuerier.getMainCategoryNames();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        categories.forEach(category -> {
            JCheckBox checkBox = new JCheckBox(category);
            checkBox.addActionListener(new MainCategoryListener(this));
            mainInnerPanel.add(checkBox);
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Application().setVisible(true);
                } catch (ClassNotFoundException | SQLException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attrInnerPanel;
    private javax.swing.JComboBox<String> attrSearchForBox;
    private javax.swing.JLabel attrSearchForLabel;
    private javax.swing.JScrollPane attributePanel;
    private javax.swing.JScrollPane businessResultPanel;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JComboBox<String> daysBox;
    private javax.swing.JComboBox<String> fromBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JComboBox<String> locationBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JScrollPane mainCategoryPanel;
    private javax.swing.JPanel mainInnerPanel;
    private javax.swing.JComboBox<String> mainSearchForBox;
    private javax.swing.JLabel mainSearchForLabel;
    private javax.swing.JPanel othersPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JDialog reviewDialog;
    private javax.swing.JScrollPane reviewDialogPanel;
    private javax.swing.JTable reviewResultTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JScrollPane subCategoryPanel;
    private javax.swing.JPanel subInnerPanel;
    private javax.swing.JComboBox<String> subSearchForBox;
    private javax.swing.JLabel subSearchForLabel;
    private javax.swing.JComboBox<String> toBox;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getAttrInnerPanel() {
        return attrInnerPanel;
    }

    public javax.swing.JComboBox<String> getAttrSearchForBox() {
        return attrSearchForBox;
    }

    public javax.swing.JScrollPane getBusinessResultPanel() {
        return businessResultPanel;
    }

    public javax.swing.JComboBox<String> getDaysBox() {
        return daysBox;
    }

    public javax.swing.JComboBox<String> getFromBox() {
        return fromBox;
    }

    public javax.swing.JComboBox<String> getLocationBox() {
        return locationBox;
    }

    public javax.swing.JPanel getMainInnerPanel() {
        return mainInnerPanel;
    }

    public javax.swing.JComboBox<String> getMainSearchForBox() {
        return mainSearchForBox;
    }

    public javax.swing.JTable getResultTable() {
        return resultTable;
    }

    public javax.swing.JDialog getReviewDialog() {
        return reviewDialog;
    }

    public javax.swing.JTable getReviewResultTable() {
        return reviewResultTable;
    }

    public javax.swing.JPanel getSubInnerPanel() {
        return subInnerPanel;
    }

    public javax.swing.JComboBox<String> getSubSearchForBox() {
        return subSearchForBox;
    }

    public javax.swing.JComboBox<String> getToBox() {
        return toBox;
    }

    public BusinessQuerier getBusinessQuerier() {
        return businessQuerier;
    }

    public CategoryQuerier getCategoryQuerier() {
        return categoryQuerier;
    }

    public ReviewQuerier getReviewQuerier() {
        return reviewQuerier;
    }
}
